# Generated by Django 5.1.5 on 2025-01-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterField(
            model_name="project",
            name="url",
            field=models.URLField(unique=True),
        ),
    ]
