# Generated by Django 5.1.5 on 2025-02-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_project_options_alter_project_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
