# Generated by Django 5.1.5 on 2025-04-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_project_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="project",
            name="url",
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
