# Generated by Django 5.1.5 on 2025-04-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_project_description_alter_project_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="url",
            field=models.URLField(max_length=1000, unique=True),
        ),
    ]
